spring.application.name=ems

spring.datasource.url=jdbc:mysql://localhost:3306/ems_java_guides
spring.datasource.username=root
spring.datasource.password=Victor_1990

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true